name: 'Prepare Release'
description: 'Interrogates the commits on a branch, since the last release, and determines the release type and release notes.'
author: 'Karl Hulme'
inputs:
  branchName:
    description: 'The name of the branch that is being targetted for release.'
    required: true
outputs:
  canRelease:
    description: 'A value of ''yes'' or ''no'' indicating if a release can be carried out.'
  releaseFailureReason:
    description: 'If ''canRelease'' is equal to ''no'' then this property will contain a reason why.'
  releaseVersion:
    description: 'The version of the new release in major.minor.patch format.'
  releaseType:
    description: 'The type of release. One of the following values: ''major'', ''minor'' or ''patch''.'
  releaseNotes:
    description: 'A formatted markdown block containing the commit comments since the last release.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'